# Optimización Bayesiana

Realizamos una regresión de proceso gaussiano para encontrar distribuciones que podrían darnos estas muestras

In [3]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process import kernels
import matplotlib.pyplot as plt
import numpy as np

In [4]:
#datos iniciales
X = np.array([[10], [2], [3], [7], [12]]).reshape(-1, 1)
y = np.array([2847, -4017, -1255, 1773, 563])

In [5]:
#fitteamos el modelo para los datos actuales
gpr = GaussianProcessRegressor(n_restarts_optimizer=10, random_state=42)

gpr.fit(X, y)
print("GaussianProcessRegressor model fitted successfully with new X and y.")

GaussianProcessRegressor model fitted successfully with new X and y.


In [6]:
#simulamos puntos de X y fiteamos con el regresor
Xsim = np.linspace(2, 15, 10001).reshape(-1, 1)
ysim, sigma = gpr.predict(Xsim, return_std=True)

In [7]:
#creamos y_upper con 2 intervalos de confianza (95%)
y_upper = ysim + 2*sigma
#buscamos el maximo con y_upper
maximo = np.argmax(y_upper)
Xsim[maximo]

array([9.9963])

In [8]:
#repetimos el proceso con la nueva "y", que nos arroja la caja negra con nuestro máximo encontrado
X2 = np.array([[10], [2], [3], [7], [12], [9.9963]]).reshape(-1, 1)
y2 = np.array([2847, -4017, -1255, 1773, 563, 2847.31363])

gpr.fit(X2, y2)

Xsim2 = np.linspace(2, 15, 10001).reshape(-1, 1)
ysim2, sigma2 = gpr.predict(Xsim2, return_std=True)

y_upper2 = ysim2 + 2*sigma2
maximo2 = np.argmax(y_upper2)
Xsim2[maximo2]

array([9.9651])

In [9]:
#repetimos el proceso con la nueva "y", que nos arroja la caja negra con nuestro máximo encontrado

X3 = np.array([[10], [2], [3], [7], [12], [9.9963], [9.9651]]).reshape(-1, 1)
y3 = np.array([2847, -4017, -1255, 1773, 563, 2847.31363, 2849.5981])

gpr.fit(X3, y3)

Xsim3 = np.linspace(2, 15, 10001).reshape(-1, 1)
ysim3, sigma3 = gpr.predict(Xsim3, return_std=True)

y_upper3 = ysim3 + 2*sigma3
maximo3 = np.argmax(y_upper3)
Xsim3[maximo3]

array([9.8741])

In [10]:
#repetimos el proceso con la nueva "y", que nos arroja la caja negra con nuestro máximo encontrado

X4 = np.array([[10], [2], [3], [7], [12], [9.9963], [9.9651], [9.8741]]).reshape(-1, 1)
y4 = np.array([2847, -4017, -1255, 1773, 563, 2847.31363, 2849.5981, 2852.69711])

gpr.fit(X4, y4)

Xsim4 = np.linspace(2, 15, 10001).reshape(-1, 1)
ysim4, sigma4 = gpr.predict(Xsim4, return_std=True)

y_upper4 = ysim4 + 2*sigma4
maximo4 = np.argmax(y_upper4)
Xsim4[maximo4]

array([9.8637])